// Filling the real official PDFs. Runs with plain `node tests/form-fill.js`.
// Zero API calls — pdf-lib from vendor/, templates from forms/.
//
// The mappings name PDF fields by string, and a PDF's field names are not
// something anyone reads until a fill silently skips one. So every name either
// mapping can emit is exercised here against the actual template, and the
// values are read back out of the saved file.

import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { fillTemplate, buildManifest } from '../src/fill.js';
import * as ssaKit from '../src/forms/ssa-starter-kit.js';
import * as dsIntake from '../src/forms/ds-intake.js';
import { toWinAnsi } from '../src/forms/common.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PDFLib = createRequire(import.meta.url)('../vendor/pdf-lib.min.js');

let failures = 0;
function check(label, cond, detail = '') {
  if (cond) return;
  failures++;
  console.error(`FAIL  ${label}${detail ? ` — ${detail}` : ''}`);
}
function eq(label, actual, expected) {
  check(label, JSON.stringify(actual) === JSON.stringify(expected),
    `got ${JSON.stringify(actual)}, want ${JSON.stringify(expected)}`);
}

const template = async spec => readFile(join(ROOT, spec.TEMPLATE));
const reopen = async bytes => (await PDFLib.PDFDocument.load(bytes)).getForm();
const textOf = (form, name) => { try { return form.getTextField(name).getText() ?? ''; } catch { return null; } };

const n = count => Array.from({ length: count }, (_, i) => i + 1);

// -- a full answer set, both forms --------------------------------------------
//
// The fixtures live in tests/fixtures/answers/*.json (generated by
// tools/golden/make-fixtures.mjs), so the goldens and the tests share them.

const fixture = async name =>
  JSON.parse(await readFile(join(ROOT, 'tests', 'fixtures', 'answers', `${name}.json`), 'utf8'));

const BOTH = await fixture('both');
const SSA_ONLY = await fixture('starter-kit');
const DS_ONLY = await fixture('ds-only');

// -- Starter Kit ---------------------------------------------------------------

{
  const mapping = ssaKit.map(BOTH);
  const { bytes, missing } = await fillTemplate(PDFLib, await template(ssaKit), mapping, {
    title: ssaKit.TITLE, addendum: ssaKit.ADDENDUM
  });
  eq('every Starter Kit field the mapping names exists', missing, []);

  const form = await reopen(bytes);
  // Every worksheet cell on the kit is reachable: a full answer set fills all 104.
  const allText = form.getFields().filter(f => f instanceof PDFLib.PDFTextField).map(f => f.getName());
  const filled = allText.filter(name => textOf(form, name));
  eq('a full answer set fills every worksheet cell', filled.length, allText.length);

  eq('row 1 uses the instruction-text field name',
    textOf(form, 'List each physical or mental condition (including emotional or learning difficulties) that limits yo'),
    'Condition number 1');
  eq('row 6 of conditions', textOf(form, 'Condition 6'), 'Condition number 6');
  eq('provider phone is formatted', textOf(form, 'Phone number 2'), '(207) 555-0020');
  eq('still seeing a provider reads Present', textOf(form, 'Date Last Seen by Provider or Discharge Date 5'), 'Present');
  eq('test date is written mm/dd/yyyy', textOf(form, 'Date 3'), '02/14/2023');
  eq('job dates are mm/yyyy', textOf(form, 'Date worked from month/year 2'), '01/2018');
  eq('pay amount', textOf(form, 'Rate of pay amount 1'), '$15');
  eq('pay frequency uses its label', textOf(form, 'Rate of pay frequency 1'), 'Per hour');
  eq('hours per day', textOf(form, 'Hours per day 3'), '8');

  const checked = form.getFields().filter(f => f instanceof PDFLib.PDFCheckBox && f.isChecked()).map(f => f.getName());
  eq('eleven checklist items are ticked', checked.length, 11);
  check('records in your possession is left for the applicant',
    !checked.some(name => name.startsWith('Records already in your possession')));

  const doc = await PDFLib.PDFDocument.load(bytes);
  check('the addendum carries the rest of the checklist', doc.getPageCount() > 5,
    `${doc.getPageCount()} pages`);
  check('the form stays editable, not flattened', form.getFields().length === 116);
}

// A ninth provider does not vanish: five on the worksheet, the rest continued.
{
  const answers = {
    ...BOTH,
    providers: n(8).map(i => ({ name: `Clinic ${i}`, phone: '2075550000' }))
  };
  const mapping = ssaKit.map(answers);
  eq('five providers go on the worksheet', mapping.text['Name of Healthcare provider 5'], 'Clinic 5');
  check('a sixth provider has no field', !Object.values(mapping.text).includes('Clinic 6'));
  const continued = mapping.tables.find(t => t.title.startsWith('B.'));
  eq('three providers continue on the addendum', continued?.rows.map(r => r[0]), ['Clinic 6', 'Clinic 7', 'Clinic 8']);
  eq('continued rows are numbered from 6', continued?.startAt, 6);
}

// The addendum holds what the kit has no fields for, and nothing DS-only.
{
  const { sections } = ssaKit.map(BOTH);
  const ids = sections.map(s => s.id);
  check('identity is in the addendum', ids.includes('identity'));
  check('direct deposit is in the addendum', ids.includes('direct_deposit'));
  check('providers are not repeated in the addendum', !ids.includes('medical_providers'));
  check('no DS-only section leaks into the Starter Kit', !ids.some(id => ['guardian', 'adl', 'ds_contact'].includes(id)),
    ids.join(', '));
  const employment = sections.find(s => s.id === 'employment');
  check('DS-only questions are not in the kit addendum',
    !employment?.blocks.some(b => b.id === 'currently_employed'));
}

// -- DS Intake Application -------------------------------------------------------

{
  const mapping = dsIntake.map(BOTH, { today: new Date(2026, 8, 19) });
  const { bytes, missing } = await fillTemplate(PDFLib, await template(dsIntake), mapping, {
    title: dsIntake.TITLE, addendum: dsIntake.ADDENDUM
  });
  eq('every DS field the mapping names exists', missing, []);

  const form = await reopen(bytes);
  const allText = form.getFields().filter(f => f instanceof PDFLib.PDFTextField).map(f => f.getName());
  // Signature dates are left for the day someone signs in ink.
  const leftBlank = new Set(['Applicant Date', 'Guardian Date', 'Other Date']);
  // Eating is rated independent in this fixture, which asks no explanation.
  const unfilled = allText.filter(name => !leftBlank.has(name) && name !== 'ExplanationEating' && !textOf(form, name));
  eq('a full answer set fills every DS text field', unfilled, []);
  for (const name of leftBlank) eq(`${name} stays blank`, textOf(form, name), '');

  eq('date at the top', textOf(form, 'Date'), '09/19/2026');
  eq('applicant name', textOf(form, 'Applicant Name'), 'Ada Lovelace');
  eq('SSN is formatted', textOf(form, 'SSN'), '123-45-6789');
  eq('place of birth is one line', textOf(form, 'Place of Birth'), 'Bangor, Maine, United States');
  eq('nine-digit zip', textOf(form, 'Zip 1'), '04101-1234');
  eq('marital status derives from the marriage history', textOf(form, 'Marital Status'), 'Never married');
  eq('helper goes in section 2', textOf(form, 'Name of PersonAgency 2'), 'Casco Bay Case Management');
  eq('emergency contact is not the guardian here', textOf(form, 'Name 4'), 'Mary Somerville');
  eq('gender radio', form.getRadioGroup('Gender').getSelected(), 'F');

  // Section 10 sits on fields named after section 11's rows.
  eq('shopping rating lands on the community-access row', textOf(form, 'LetterFamily'), 'B');
  eq('family relationships land on the _2 row', textOf(form, 'LetterFamily_2'), 'D');
  eq('an independent rating has no explanation', textOf(form, 'ExplanationEating'), '');
  eq('other ratings carry their explanation', textOf(form, 'ExplanationCooking'), 'Needs practice with cooking');

  eq('confirmed diagnoses fill all three rows',
    textOf(form, 'Current Diagnoses Confirmed by Psychological evaluation with IQ and Adaptive Scores 3'), 'ADHD');
  eq('special education and 504 plan share one box',
    textOf(form, 'Have you ever received Special Education andor 504 Plan'), 'Special education: Yes; 504 plan: No');
  eq('work history comes from the Starter Kit job list',
    textOf(form, 'Employment History')?.startsWith('Title 1, Employer 1 (01/2018 to Present)'), true);

  const checked = ['Check Box26', 'Check Box27', 'Check Box28', 'Check Box29', 'Check Box30']
    .filter(name => form.getCheckBox(name).isChecked());
  eq('document checkboxes', checked, ['Check Box26', 'Check Box27', 'Check Box29', 'Check Box30']);
}

// A long list is shrunk, then cut and continued — never silently dropped.
{
  const answers = {
    ...BOTH,
    conditions: n(14).map(i => ({ name: `A fairly long diagnosis name number ${i}` }))
  };
  const mapping = dsIntake.map(answers);
  const { bytes, overflowText } = await fillTemplate(PDFLib, await template(dsIntake), mapping, {
    addendum: dsIntake.ADDENDUM
  });
  const form = await reopen(bytes);
  const box = textOf(form, 'Current Diagnoses');
  check('the box says to see the attached page', box.endsWith('(see attached)'), box);
  const spilled = overflowText.find(o => o.label === 'Current diagnoses');
  check('the full list goes to the addendum', spilled?.value.includes('number 14'), JSON.stringify(spilled));
  check('the addendum page was added', (await PDFLib.PDFDocument.load(bytes)).getPageCount() > 4);
}

// DS without the Starter Kit uses its own questions for the shared facts.
{
  const answers = {
    forms: 'ds', marital_status: 'divorced',
    diagnoses: [{ name: 'Down syndrome' }],
    ds_jobs: [{ employer: 'Hannaford', job_title: 'Bagger', start: '2022-05', end: 'present' }],
    // Starter Kit answers that should be ignored now.
    marriages: [{ spouse_name: 'X', still_active: true }],
    jobs: [{ employer: 'Ignored' }]
  };
  const mapping = dsIntake.map(answers);
  eq('marital status is asked directly', mapping.text['Marital Status'], 'Divorced');
  eq('diagnoses come from the DS list', mapping.text['Current Diagnoses'], 'Down syndrome');
  eq('work history comes from the DS list', mapping.text['Employment History'], 'Bagger, Hannaford (05/2022 to Present)');
  check('no guardian, no guardian name printed', !('Guardian Name print' in mapping.text));
  eq('emergency contact left blank when not given', mapping.text['Name 4'], undefined);
}

// The guardian doubles as emergency contact when they say so.
{
  const mapping = dsIntake.map({ ...BOTH, ec_same_as_guardian: true, ec_name: undefined });
  eq('guardian copied into section 4', mapping.text['Name 4'], 'Anne Byron');
  eq('with their relationship', mapping.text['Relationship 4'], 'Mother');
}

// Marital status derived from a marriage history.
{
  const both = extra => dsIntake.maritalStatus({ forms: 'both', ...extra });
  eq('active marriage', both({ marriages: [{ still_active: false }, { still_active: true }] }), 'Married');
  eq('last spouse died', both({ marriages: [{ still_active: false, spouse_died: true }] }), 'Widowed');
  eq('ended otherwise', both({ marriages: [{ still_active: false, spouse_died: false }] }), 'Divorced');
  eq('never asked', both({}), '');
}

// A name the standard fonts cannot draw does not break the download.
{
  eq('Latin-1 survives', toWinAnsi('José Ñúñez'), 'José Ñúñez');
  eq('letters outside Latin-1 fall back to their base letter', toWinAnsi('Łukasz Wałęsa'), 'Lukasz Walesa');
  eq('scripts with no Latin form become ?', toWinAnsi('李'), '?');
  const answers = { ...BOTH, first_name: 'Łukasz', last_name: '李' };
  const { bytes, missing } = await fillTemplate(PDFLib, await template(dsIntake), dsIntake.map(answers), {});
  eq('a non-Latin name still fills', missing, []);
  check('and produces a PDF', bytes.length > 1000);
}

// A newline inside a single-line value used to throw inside fitText.
{
  const answers = { ...BOTH, first_name: 'Ada\nMarie' };
  const { bytes, missing } = await fillTemplate(PDFLib, await template(dsIntake), dsIntake.map(answers), {});
  eq('a newline in a single-line box does not break the fill', missing, []);
  const form = await reopen(bytes);
  eq('the newline is flattened to a space', textOf(form, 'Applicant Name'), 'Ada Marie Lovelace');
}

// The default appearance stays in the form's own vocabulary.
{
  const answers = { ...BOTH };
  const { bytes } = await fillTemplate(PDFLib, await template(dsIntake), dsIntake.map(answers), {});
  const doc = await PDFLib.PDFDocument.load(bytes);
  const form = doc.getForm();
  // Every font resource the form's /DR knows. A DA naming a font outside this
  // set leaves Acrobat without a font to regenerate the appearance.
  const af = doc.context.lookup(doc.catalog.get(PDFLib.PDFName.of('AcroForm')));
  const dr = af.get(PDFLib.PDFName.of('DR'));
  const fontNames = new Set();
  dr.get(PDFLib.PDFName.of('Font')).entries().forEach(([k]) => fontNames.add(k.asString()));

  // Field DAs and widget DAs both: a viewer regenerating an appearance uses
  // the widget's own DA when it has one, and the DS form has 86 of those.
  const fontOf = da => /(\/[\w-]+)[\s\S]*?[\d.]+\s+Tf/.exec(da ?? '')?.[1];
  const bad = [];
  let widgetDas = 0;
  for (const f of form.getFields()) {
    if (!(f instanceof PDFLib.PDFTextField)) continue;
    const fieldFont = fontOf(f.acroField.getDefaultAppearance());
    if (fieldFont && !fontNames.has(fieldFont)) bad.push(`${f.getName()} -> ${fieldFont}`);
    f.acroField.getWidgets().forEach((w, i) => {
      const da = w.getDefaultAppearance();
      if (!da) return;
      widgetDas++;
      const font = fontOf(da);
      if (font && !fontNames.has(font)) bad.push(`${f.getName()} widget ${i} -> ${font}`);
    });
  }
  check('the DS form has widget-level DAs to check', widgetDas > 50, `found ${widgetDas}`);
  eq('every filled field and widget DA names a font in /DR', bad, []);
}

// The widget-level DA no longer overrides the fitted size.
{
  const answers = { ...BOTH };
  const mapping = dsIntake.map(answers, { today: new Date(2026, 8, 19) });
  // A value far too long for any box: the plan must shrink it below the
  // printed size, and the saved DA must agree with the plan's fit.
  const long = 'A Very Long Applicant Name That Must Shrink '.repeat(6);
  const shrunk = { ...mapping, text: { ...mapping.text, 'Applicant Name': long } };
  const { bytes } = await fillTemplate(PDFLib, await template(dsIntake), shrunk, {});
  const form = await reopen(bytes);
  const field = form.getTextField('Applicant Name');
  const da = field.acroField.getDefaultAppearance();
  const size = /([\d.]+)\s+Tf/.exec(da)?.[1];
  check('the field DA carries a fitted size, not the printed one', size && Number(size) < 10, da);
  const widgetDa = field.acroField.getWidgets().map(w => w.getDefaultAppearance()).filter(Boolean);
  const widgetSize = /([\d.]+)\s+Tf/.exec(widgetDa[0] ?? '')?.[1];
  eq('the widget DA matches the field DA size', widgetSize, size);
}

console.log(failures ? `\n${failures} failure(s)` : 'form-fill: all checks passed');
process.exit(failures ? 1 : 0);
