// The canonical parse corpus: every val/defer case the local parser is pinned
// to. Shared by tests/parse-local.js (assertions) and tools/golden/index.mjs
// (the `parse` golden the Kotlin port is compared against), so the two cannot
// drift. `optionsKey` names a schema question whose option list the case
// needs; the generator resolves it to the options themselves. `questionKey`
// names a schema question to run the case against whole — its prompt, `per`
// and `kind` — for the cases whose answer depends on what was asked.

export const VALUE_CASES = [
  // -- yes / no
  ...['yes', 'Yes', 'yeah', 'yep', 'yup', 'sure', 'correct', 'right',
    'true', 'affirmative', 'ok', 'okay', "that's right", 'uh huh', 'Yes.', 'yes!']
    .map(input => ({ type: 'yesno', input, value: true })),
  ...['no', 'No', 'nope', 'nah', 'negative', 'false', 'incorrect',
    'wrong', "that's wrong", 'uh uh', 'No.']
    .map(input => ({ type: 'yesno', input, value: false })),
  { type: 'yesno', input: 'um, yes', value: true },
  { type: 'yesno', input: 'well no', value: false },
  // Parser v2: a yes or no said as a full clause.
  { type: 'yesno', input: 'yes I do', value: true },
  { type: 'yesno', input: 'yes, I do', value: true },
  { type: 'yesno', input: 'yeah she does', value: true },
  { type: 'yesno', input: 'no I do not', value: false },
  { type: 'yesno', input: 'no she does not', value: false },
  { type: 'yesno', input: "no she doesn't", value: false },
  { type: 'yesno', input: "no it isn't", value: false },
  { type: 'yesno', input: 'yes, I do.', value: true },
  { type: 'yesno', input: 'no I don\u2019t', value: false },
  { type: 'yesno', input: 'that\u2019s right', value: true },

  // -- sensitive digits
  { type: 'ssn', input: '123456789', value: '123456789' },
  { type: 'ssn', input: '123 45 6789', value: '123456789' },
  { type: 'ssn', input: '123-45-6789', value: '123456789' },
  { type: 'ssn', input: 'one two three four five six seven eight nine', value: '123456789' },
  { type: 'ssn', input: 'one two three dash four five dash six seven eight nine', value: '123456789' },
  { type: 'ssn', input: '9, 8, 7, 6, 5, 4, 3, 2, 1', value: '987654321' },
  { type: 'ssn', input: '123, 45, 6789', value: '123456789' },
  { type: 'ssn', input: '123.45.6789', value: '123456789' },
  // An echo of the question is stripped, even before digits (see stripEcho).
  { type: 'ssn', questionKey: 'ssn', input: 'My Social Security number is 123 45 6789', value: '123456789' },
  { type: 'ssn', input: 'five five five oh one two three four', value: '55501234' },
  { type: 'routing', input: 'nine eight seven six five four three two one', value: '987654321' },
  { type: 'account', input: '4321', value: '4321' },

  // -- phone
  { type: 'phone', input: '5551234567', value: '5551234567' },
  { type: 'phone', input: '555 123 4567', value: '5551234567' },
  { type: 'phone', input: '(555) 123-4567', value: '5551234567' },
  { type: 'phone', input: 'five five five one two three four five six seven', value: '5551234567' },

  // -- dates
  { type: 'date', input: '1979-03-14', value: '1979-03-14' },
  { type: 'date', input: '3/14/79', value: '1979-03-14' },
  { type: 'date', input: '03-14-1979', value: '1979-03-14' },
  { type: 'date', input: 'March 14th 1979', value: '1979-03-14' },
  { type: 'date', input: 'march 14 1979', value: '1979-03-14' },
  { type: 'date', input: 'the 14th of March 1979', value: '1979-03-14' },
  { type: 'date', input: 'March 14th, 1979', value: '1979-03-14' },
  { type: 'date', input: 'Mar 14 1979', value: '1979-03-14' },
  { type: 'date', input: 'um, March 14th 1979', value: '1979-03-14' },
  { type: 'date', input: 'March 14th 79', value: '1979-03-14' },
  { type: 'date', input: 'January 1st 05', value: '2005-01-01' },
  { type: 'date', input: 'March fourteenth nineteen seventy nine', value: '1979-03-14' },
  { type: 'date', input: 'march fourteenth, nineteen seventy-nine', value: '1979-03-14' },
  { type: 'date', input: 'the fourteenth of March nineteen seventy nine', value: '1979-03-14' },
  { type: 'date', input: 'March 14 1979', value: '1979-03-14' },
  { type: 'date', input: 'June second nineteen oh five', value: '1905-06-02' },
  { type: 'date', input: 'July fourth nineteen seventy six', value: '1976-07-04' },
  { type: 'date', input: 'May fifth twenty twelve', value: '2012-05-05' },
  { type: 'date', input: 'August eighth twenty twenty four', value: '2024-08-08' },
  { type: 'date', input: 'January first two thousand', value: '2000-01-01' },
  { type: 'date', input: 'October tenth two thousand eighteen', value: '2018-10-10' },
  { type: 'date', input: 'March twenty first two thousand and five', value: '2005-03-21' },
  { type: 'date', input: 'December thirty first nineteen ninety nine', value: '1999-12-31' },
  { type: 'date', input: 'February twenty ninth two thousand twenty', value: '2020-02-29' },
  { type: 'monthyear', input: 'March nineteen seventy nine', value: '1979-03' },
  { type: 'monthyear', input: 'August two thousand fifteen', value: '2015-08' },
  { type: 'date', input: 'March the 14th, 1979', value: '1979-03-14' },
  { type: 'date', input: 'it is March 14th 1979', value: '1979-03-14' },
  { type: 'date', input: '1979 March 14', value: '1979-03-14' },
  { type: 'date', input: '1979, March 14th', value: '1979-03-14' },
  { type: 'date', input: '12/11/1979', value: '1979-12-11' },

  // -- month / year
  { type: 'monthyear', input: '1979-03', value: '1979-03' },
  { type: 'monthyear', input: 'March 1979', value: '1979-03' },
  { type: 'monthyear', input: 'march of 79', value: '1979-03' },
  { type: 'monthyear', input: '3/79', value: '1979-03' },
  { type: 'monthyear', input: 'August 2015', value: '2015-08' },
  { type: 'monthyear', input: 'still working', value: 'present' },
  { type: 'monthyear', input: 'still seeing them', value: 'present' },
  { type: 'monthyear', input: 'ongoing', value: 'present' },
  { type: 'monthyear', input: 'I still go there', value: 'present' },
  { type: 'monthyear', input: 'currently', value: 'present' },
  { type: 'monthyear', input: 'still March 2015', value: '2015-03' },

  // -- money and numbers
  { type: 'money', input: '1200', value: 1200 },
  { type: 'money', input: '$1,200', value: 1200 },
  { type: 'money', input: '1200 dollars', value: 1200 },
  { type: 'money', questionKey: 'monthly_amount', input: 'about $1,200 a month', value: 1200 },
  { type: 'money', questionKey: 'monthly_amount', input: 'twelve hundred monthly', value: 1200 },
  { type: 'number', input: '3', value: 3 },
  { type: 'number', input: '12', value: 12 },
  { type: 'money', input: 'twelve hundred', value: 1200 },
  { type: 'money', input: 'two thousand five', value: 2005 },
  { type: 'money', input: 'two thousand and five', value: 2005 },
  { type: 'money', input: 'two thousand five hundred thirty', value: 2530 },
  { type: 'money', input: 'a hundred and five', value: 105 },
  { type: 'number', input: 'twenty five', value: 25 },
  { type: 'number', input: 'twenty', value: 20 },
  // A job's pay: the period is asked next, so any period said now is dropped.
  { type: 'money', questionKey: 'pay_amount', input: '$20 an hour', value: 20 },
  { type: 'money', questionKey: 'pay_amount', input: 'twenty dollars a week', value: 20 },
  { type: 'money', questionKey: 'pay_amount', input: 'fifteen hourly', value: 15 },
  { type: 'money', questionKey: 'pay_amount', input: '12 an hour', value: 12 },
  { type: 'money', questionKey: 'pay_amount', input: '$900 every two weeks', value: 900 },
  { type: 'money', input: 'eighty five hundred', value: 8500 },
  { type: 'money', input: 'twenty five hundred', value: 2500 },
  { type: 'money', input: 'fifteen hundred and fifty', value: 1550 },
  { type: 'money', input: 'a thousand', value: 1000 },
  { type: 'money', input: 'two hundred thousand', value: 200000 },
  { type: 'number', questionKey: 'hours_per_day', input: 'eight a day', value: 8 },
  // A question that asks for a year reads a spoken year as one.
  { type: 'number', questionKey: 'education_year', input: 'nineteen ninety eight', value: 1998 },
  { type: 'number', questionKey: 'education_year', input: 'twenty ten', value: 2010 },
  { type: 'number', questionKey: 'education_year', input: 'two thousand ten', value: 2010 },
  { type: 'number', questionKey: 'education_year', input: '1998', value: 1998 },

  // -- free text
  ...['John', 'Springfield', 'Dr. Smith at City Clinic']
    .map(input => ({ type: 'text', input, value: input })),
  { type: 'text', input: 'diabetes', value: 'Diabetes' },
  { type: 'text', input: 'Maine Medical Center in Portland.', value: 'Maine Medical Center in Portland' },
  { type: 'text', input: 'um, the Maine Medical Center.', value: 'The Maine Medical Center' },
  { type: 'text', input: 'uh, uh John Smith', value: 'John Smith' },
  { type: 'text', input: 'My answer is: retired teacher.', value: 'Retired teacher' },
  { type: 'text', input: 'Well Street', value: 'Well Street' },
  { type: 'text', input: 'So-Young Kim', value: 'So-Young Kim' },
  { type: 'text', input: 'Okay Corral Road', value: 'Okay Corral Road' },
  { type: 'text', input: 'um', value: 'Um' },

  // -- choice
  { type: 'choice', input: 'the starter kit', value: 'ssa', optionsKey: 'forms' },
  { type: 'choice', input: 'Starter Kit.', value: 'ssa', optionsKey: 'forms' },
  { type: 'choice', input: 'developmental services', value: 'ds', optionsKey: 'forms' },
  { type: 'choice', input: "um, it's the Maine application", value: 'ds', optionsKey: 'forms' },
  { type: 'choice', input: 'both', value: 'both', optionsKey: 'forms' },
  { type: 'choice', input: 'both of them please', value: 'both', optionsKey: 'forms' },
  { type: 'choice', input: 'the starter kit and developmental services', value: 'both', optionsKey: 'forms' },
  { type: 'choice', input: 'independent', value: 'A', optionsKey: 'eating_level' },
  { type: 'choice', input: 'B', value: 'B', optionsKey: 'eating_level' },
  { type: 'choice', input: 'letter c', value: 'C', optionsKey: 'eating_level' },
  { type: 'choice', input: 'dee', value: 'D', optionsKey: 'eating_level' },
  { type: 'choice', input: 'needs supervision', value: 'B', optionsKey: 'eating_level' },
  { type: 'choice', input: 'they need physical assistance', value: 'D', optionsKey: 'eating_level' },
  { type: 'choice', input: 'total assistance', value: 'E', optionsKey: 'eating_level' },
  { type: 'choice', input: 'needs skills training', value: 'C', optionsKey: 'eating_level' },
  { type: 'choice', input: 'every two weeks', value: 'biweekly', optionsKey: 'pay_frequency' },
  { type: 'choice', input: 'hourly', value: 'hour', optionsKey: 'pay_frequency' },
  { type: 'choice', input: 'twice a month', value: 'twice_month', optionsKey: 'pay_frequency' },
  { type: 'choice', input: 'per year', value: 'year', optionsKey: 'pay_frequency' },
  { type: 'choice', input: 'never married', value: 'never_married', optionsKey: 'marital_status' },
  { type: 'choice', input: 'widowed', value: 'widowed', optionsKey: 'marital_status' },

  // -- zip and email
  { type: 'zip', input: '04101', value: '04101' },
  { type: 'zip', input: 'oh four one oh one', value: '04101' },
  { type: 'zip', input: '04101-1234', value: '041011234' },
  { type: 'email', input: 'Jane.Doe@Example.com', value: 'jane.doe@example.com' },
  { type: 'email', input: 'jane dot doe at example dot com', value: 'jane.doe@example.com' }
];

export const DEFER_CASES = [
  { type: 'yesno', input: 'yes but actually no' },
  { type: 'yesno', input: 'no wait, yes' },
  { type: 'yesno', input: 'yes I worked there until 2019' },
  { type: 'yesno', input: 'go back' },
  { type: 'yesno', input: 'I think so' },
  { type: 'yesno', input: 'maybe' },
  { type: 'yesno', input: 'can you repeat that' },
  // A full clause has to be the whole answer: a second polarity after the
  // first is two answers, not one.
  { type: 'yesno', input: 'yes I do not' },
  { type: 'yesno', input: 'yes she does not' },
  { type: 'yesno', input: 'yes I did but not anymore' },
  { type: 'yesno', input: 'yes I do, no wait' },
  { type: 'yesno', input: "no I don't, yes I do" },
  { type: 'ssn', input: 'double seven three four five six seven eight nine' },
  { type: 'ssn', input: 'triple oh one two three four five six' },
  { type: 'ssn', input: 'seventeen twenty three forty five sixty seven' },
  { type: 'ssn', input: 'my social is 123 45 6789' },
  { type: 'ssn', input: 'I do not remember' },
  { type: 'ssn', input: 'it starts with 123' },
  { type: 'account', input: 'the one ending in 4321' },
  { type: 'phone', input: 'you can reach me at 555 123 4567' },
  { type: 'date', input: 'February thirtieth nineteen ninety' },
  { type: 'date', input: 'March fourteenth two thousand ninety nine' },
  { type: 'date', input: 'sometime in the eighties' },
  { type: 'date', input: '14/3/1979' },
  { type: 'date', input: 'February 30 1990' },
  { type: 'date', input: 'February 30th, 1990' },
  { type: 'date', input: 'March 32nd 1979' },
  { type: 'date', input: 'March 14th 2099' },
  { type: 'date', input: 'next Tuesday' },
  { type: 'date', input: 'I do not remember exactly' },
  { type: 'date', input: 'March 1979' },
  { type: 'monthyear', input: 'a few years ago' },
  { type: 'monthyear', input: 'March 2099' },
  { type: 'money', input: 'eight hundred to a thousand' },
  { type: 'money', input: 'between 800 and 1000' },
  { type: 'money', input: '800 or 900' },
  { type: 'money', input: 'five and six' },
  { type: 'number', input: 'a few' },
  // Runs of number words that are not one number. Summing them invents one.
  { type: 'number', input: 'nineteen ninety eight' },
  { type: 'number', input: 'twenty ten' },
  { type: 'money', input: 'three fifty' },
  { type: 'money', input: 'eleven fifty' },
  { type: 'money', questionKey: 'pay_amount', input: 'eleven fifty an hour' },
  { type: 'number', input: 'one two three' },
  { type: 'number', input: 'five six' },
  { type: 'money', input: 'twenty twenty' },
  { type: 'money', input: 'hundred' },
  { type: 'money', input: 'thousand' },
  { type: 'money', input: 'a hundred and five and six' },
  { type: 'money', input: 'twelve hundred thousand' },
  { type: 'money', input: 'a hundred and' },
  // A period that contradicts the question, or any period where it has none.
  { type: 'money', questionKey: 'monthly_amount', input: '$20 an hour' },
  { type: 'money', questionKey: 'monthly_amount', input: 'fifteen hundred a year' },
  { type: 'money', questionKey: 'value', input: '$500 a month' },
  { type: 'money', input: '$20 an hour' },
  { type: 'number', questionKey: 'hours_per_day', input: 'forty a week' },
  // The unit noun is not stripped, so this is still asked again.
  { type: 'number', questionKey: 'days_per_week', input: 'five days a week' },
  { type: 'money', questionKey: 'pay_amount', input: '$50 twice a week' },
  // Not digits, whatever a lookup table's prototype says.
  { type: 'ssn', input: 'constructor' },
  { type: 'account', input: '1234 constructor' },
  { type: 'number', input: 'constructor' },
  { type: 'text', input: '...' },
  { type: 'text', input: ' . ' },
  { type: 'choice', input: 'not the starter kit', optionsKey: 'forms' },
  { type: 'choice', input: 'I am not sure', optionsKey: 'forms' },
  { type: 'choice', input: 'the blue one', optionsKey: 'forms' },
  { type: 'choice', input: 'a little help sometimes', optionsKey: 'eating_level' },
  { type: 'choice', input: 'supervision or training', optionsKey: 'eating_level' },
  { type: 'choice', input: "doesn't need supervision", optionsKey: 'eating_level' },
  { type: 'zip', input: '4101' },
  { type: 'zip', input: 'Portland' },
  { type: 'email', input: 'jane at the office' },
  { type: 'email', input: 'I do not have one' }
];
