// Pure Kotlin/JVM: everything the interview does that has no Android surface.
// The JS reference (src/*.js at the repo root) is the source of truth, and the
// golden fixtures in core/src/test/resources/golden/ (generated by
// tools/golden/*.mjs) pin this port to it, run on both the desktop JVM and
// (via :pdf and :app instrumented tests) under Android's ICU.
plugins {
    alias(libs.plugins.kotlin.jvm)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation(libs.kotlinx.coroutines.core)
    testImplementation(libs.junit)
}

// The interview schema is data, exported by the JS reference: the app loads
// the same file the goldens and the web app answer from. It is copied into
// build/, never into src/, so tools/schema.json stays the only copy anyone
// edits or commits.
val syncSchema = tasks.register<Copy>("syncSchema") {
    from("${rootProject.projectDir}/../tools/schema.json")
    into(layout.buildDirectory.dir("generated/schema-resources"))
}

sourceSets.named("main") {
    resources.srcDir(syncSchema)
}

// The turn scenarios are shared between the JS and Kotlin implementations;
// they are copied into the test resources pinned by hash, exactly like
// :pdf's forms and :speech's audio, so the Kotlin test runs the same files
// the turn golden was generated from. The answer fixtures feed the
// `resume` scenarios.
val syncScenarios = tasks.register<CopyPinnedAssets>("syncScenarios") {
    sourceDir = file("${rootProject.projectDir}/../tools/turn-scenarios")
    pins = file("turn-scenarios.SHA256SUMS")
    assetPath = "turn-scenarios"
    outputDir = layout.buildDirectory.dir("generated/scenario-resources/scenarios")
}

val syncFixtures = tasks.register<CopyPinnedAssets>("syncFixtures") {
    sourceDir = file("${rootProject.projectDir}/../tests/fixtures/answers")
    pins = file("answer-fixtures.SHA256SUMS")
    assetPath = "fixtures/answers"
    outputDir = layout.buildDirectory.dir("generated/scenario-resources/fixtures")
}

sourceSets.named("test") {
    resources.srcDir(syncScenarios)
    resources.srcDir(syncFixtures)
}

tasks.test {
    useJUnit()
    testLogging {
        events("failed", "skipped")
        showStackTraces = true
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
}
