// Pure Kotlin/JVM: everything the interview does that has no Android surface.
// The JS reference (src/*.js at the repo root) is the source of truth, and the
// golden fixtures in core/src/test/resources/golden/ (generated by
// tools/golden/*.mjs) pin this port to it, run on both the desktop JVM and
// (via :pdf and :app instrumented tests) under Android's ICU.
plugins {
    alias(libs.plugins.kotlin.jvm)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation(libs.kotlinx.coroutines.core)
    testImplementation(libs.junit)
}

// The interview schema is data, exported by the JS reference: the app loads
// the same file the goldens and the web app answer from. It is copied into
// build/, never into src/, so tools/schema.json stays the only copy anyone
// edits or commits.
val syncSchema = tasks.register<Copy>("syncSchema") {
    from("${rootProject.projectDir}/../tools/schema.json")
    into(layout.buildDirectory.dir("generated/schema-resources"))
}

sourceSets.named("main") {
    resources.srcDir(syncSchema)
}

tasks.test {
    useJUnit()
    testLogging {
        events("failed", "skipped")
        showStackTraces = true
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
}
